### ISSUE TITLE
1.16 TODO

### ISSUE THREAD

**Issue by ds58** [Ruinscraft/mcatlas-issues#84]
## Feature changes
- [x] [Ensure all new items from 1.14-1.16 are obtainable](https://github.com/Ruinscraft/mcatlas-issues/issues/73)
- [ ] ~~Figure out if and where to put new biomes~~ - saved for later update
- [x] Reconfigure mob nerfing
- [x] [Create world generator for nether (disables gold ore spawning, etc)](https://github.com/Ruinscraft/mcatlas-environment/blob/master/src/main/java/net/mcatlas/environment/NetherPopulator.java)
- [x] Add anti-xray configuration to nether including regular nether blocks AND blocks added in the world generator
- [x] Disable phantoms
- [x] Figure out village raiding
- [x] Weaken firework crossbows
- [x] [/near command should not show people with vanish potion effect](https://github.com/Ruinscraft/mcatlas-helpers/commit/ad4d9e1120836b5ead2a26af04e25b5accb9b2c7)
- [x] [Add prevention for bonemealing Towns you can't build in](https://github.com/Ruinscraft/mcatlas-towny-helpers/issues/1)
- [x] [Add PVP countdown when toggling PVP (either on or off)](https://github.com/Ruinscraft/mcatlas-towny-helpers/blob/master/src/main/java/net/mcatlas/towny/helpers/TownPVPToggleTimer.java)
- [x] [Add teleport confirmation if teleporting to a town with PVP enabled (or about to be enabled)](https://github.com/Ruinscraft/mcatlas-towny-helpers/blob/master/src/main/java/net/mcatlas/towny/helpers/TownPVPToggleTimer.java)
- [x] Update PVP rules to reflect new PVP toggle and teleport confirmation systems
- [x] Remove/change useless vote rewards (maybe shulker shells)
- [ ] ~~[Tools for moderators](https://github.com/Ruinscraft/mcatlas-issues/issues/85)~~ - at a later date
- [x] [Fix "cannot place boats on land"](https://github.com/Ruinscraft/mcatlas-issues/issues/40)

## Other technical
- [x] Pregen 2500x2500 ish region of new nether with new world generator
- [x] Convert towny data to the new schema and test
- [x] [Create new void chunk generator, remove VoidGenerator](https://github.com/Ruinscraft/mcatlas-environment/commit/bd32c9c58caeedf94459b27f1f8d4583cc03eb0b)
- [x] Delete column `plotManagementRevertSpeed` from TOWNY_WORLDS
- [x] Increase default render distance to 7 - per-player render distance not implemented on 1.16 yet
- [x] Reset logblock logs for the nether
- [x] Check logblock config, make sure it isn't logging end worlds

## Plugin Updates
Strikethrough does not require an update
Checkbox and Bold has already been updated by Ruinscraft
Checkbox has already been updated by 3rd party

- [x] ~~BuycraftX~~
- [x] **DukesMart**
- [x] dynmap
- [x] ~~Dynmap-Towny~~ - Should continue to work fine with updated Towny
- [x] FarmLimiter
- [x] HeadDatabase
- [x] ~~Hordes~~ - won't be using
- [x] IllegalStack
- [x] **LockettePro** - Needs testing
- [x] LogBlock
- [x] ~~LuckPerms~~
- [x] ~~MineLink~~
- [x] NoCheatPlus
- [x] ~~NovaBroadcast~~
- [x] OpenInv
- [x] **Panilla**
- [x] PlayerHeads
- [x] PlugMan
- [x] **Powder**
- [x] ProtocolLib
- [x] SAML
- [x] SuperbVote
- [x] Towny
- [x] ~~TownyNameUpdater~~ - no longer needed
- [x] Vault
- [x] ~~VoidGenerator~~ - replaced with generator in mcatlas-environment
- [x] ~~VotifierPlayerEnforcer~~
- [x] cncp - Now included in NCP I believe. We can remove
- [x] ~~dynmap-countries~~ - Shouldn't require changes with new dynmap
- [x] mcmmo
- [x] ~~mcatlas-economy~~
- [x] ~~mcatlas-end~~
- [x] ~~mcatlas-environment~~
- [x] **mcatlas-helpers** - ~~Remove towny depen. Put in mcatlas-towny-helpers~~
- [x] ~~mcatlas-teleporting~~
- [x] **mcatlas-towny-helpers**
- [x] nuvotifier
- [x] **ruinscraft-chat** - ~~Update towny depen~~
- [x] ~~ruinscraft-combat-log~~
- [x] ~~ruinscraft-death-messages~~
- [x] ~~ruinscraft-discord-auth~~
- [x] ~~ruinscraft-gambling~~
- [x] ~~ruinscraft-high-ping-kick~~
- [x] ~~ruinscraft-motd~~
- [x] ~~ruinscraft-punishments~~
- [x] ~~ruinscraft-slashserver~~
- [x] ruinscraft-stickers - Remove from server
- [x] WorldEdit
- [x] WorldGuard
